function [Sigmas, Mus, Ps] = loadGMMparams(path)
% LOADGMMPARAMS Loads the GMM parameters generated by pyGMM (or other) and returns them.
%   [SIGMAS, MUS, PS] = LOAGGMMPARAMS(PATH) loads the python-dat.mat file
%   in the given path. Path must be an existing directory. The mat file
%   must contain three fields in the following order: 1) The covariance(s)
%   parameter(s), 2) the mean value(s) parameter(s) and 3) the
%   proprotions parameter.
%
%   See also GETGMMPARAMS.
arguments
    path (1, :) string
end
if ~exists(path, "dir")
    throw( ...
        MException( ...
        "GMM:loadGMMparams:NonexistentDirectory", ...
        "Directory " + path + " does not exist." ...
        ) ...
        )
end
vars = getfield(load(path + "/python-data.mat"), "varargin");
Sigmas = vars{1};
Mus = vars{2};
Ps = vars{3};
end